// donoroverview.style.js
// All styles for DonorOverview page

const donorOverviewStyles = {
  container: {
    width: '100%',
    height: '100%',
    background: '#f9f9f9',
    display: 'flex',
    flexDirection: 'row',
  },
  leftColumn: {
    width: '50%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
  },
  topRow: {
    height: undefined, // dynamic
    minHeight: 100,
    background: '#fff',
    borderRadius: 8,
    margin: 24,
    marginBottom: 0,
    boxShadow: '0 2px 8px #0001',
    overflow: 'hidden',
    display: 'flex',
  },
  childGrid: {
    flex: 1,
    borderRight: '1px solid #eee',
    padding: 16,
    overflow: 'auto',
  },
  childTable: {
    width: '100%',
    fontSize: 15,
    background: '#f7f8fa',
    borderCollapse: 'separate',
    borderSpacing: 0,
  },
  childThCheckbox: {
    width: 36,
    padding: '10px 0 10px 16px',
    background: '#f7f8fa',
    border: 'none',
  },
  childThId: {
    textAlign: 'left',
    padding: '10px 16px',
    color: '#222',
    fontWeight: 600,
    background: '#f7f8fa',
    border: 'none',
    fontSize: 13,
    width: 40,
  },
  childThDoc: {
    textAlign: 'left',
    padding: '10px 16px 10px 0',
    color: '#222',
    fontWeight: 600,
    background: '#f7f8fa',
    border: 'none',
    fontSize: 13,
  },
  childTr: (selected) => ({
    background: selected ? '#e3eafc' : 'transparent',
    cursor: 'pointer',
    borderRadius: 4,
  }),
  childTdCheckbox: {
    padding: '8px 0 8px 16px',
    border: 'none',
  },
  childTd: {
    padding: '8px 16px',
    color: '#222',
    border: 'none',
    fontSize: 14,
  },
  childTdDoc: {
    padding: '8px 16px 8px 0',
    color: '#222',
    border: 'none',
    fontSize: 14,
  },
  info: {
    flex: 1,
    padding: 16,
    overflow: 'auto',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  infoTitle: {
    color: '#222',
    fontWeight: 600,
    marginBottom: 12,
    fontSize: 15,
  },
  infoText: {
    margin: '8px 0',
    color: '#222',
  },
  rowResizeHandle: {
    height: 8,
    cursor: 'row-resize',
    background: '#e0e0e0',
    width: 'calc(100% - 48px)',
    margin: '0 24px',
    borderRadius: 4,
    zIndex: 2,
  },
  mainGrid: {
    flex: 1,
    background: '#fff',
    borderRadius: 8,
    boxShadow: '0 2px 8px #0001',
    margin: 24,
    marginTop: 0,
    overflow: 'auto',
    padding: 0,
    minHeight: 100,
  },
  mainTable: {
    width: '100%',
    borderCollapse: 'separate',
    borderSpacing: 0,
    background: '#f7f8fa',
  },
  mainTh: {
    padding: '10px 16px',
    color: '#222',
    fontWeight: 600,
    background: '#f7f8fa',
    border: 'none',
    fontSize: 13,
  },
  mainTr: {
    borderRadius: 4,
  },
  mainTd: {
    padding: '8px 16px',
    color: '#222',
    border: 'none',
    fontSize: 14,
  },
  mainTdBold: {
    padding: '8px 16px',
    color: '#222',
    border: 'none',
    fontSize: 14,
    fontWeight: 600,
  },
  rightColumn: {
    width: '50%',
    height: '100%',
    padding: 24,
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
  },
  pdfContainer: {
    flex: 1,
    width: '100%',
    height: '100%',
    background: '#222',
    borderRadius: 8,
    boxShadow: '0 2px 8px #0001',
    overflow: 'hidden',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  pdfInner: {
    width: '100%',
    height: '100%',
    position: 'relative',
  },
};

export default donorOverviewStyles;
